# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mimetype-fu}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Josh French", "Jan Schwenzien"]
  s.date = %q{2011-04-18}
  s.description = %q{get the mimetype of a file directly in Ruby}
  s.email = %q{josh@vitamin-j.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "init.rb",
    "install.rb",
    "lib/extensions_const.rb",
    "lib/mime_types.yml",
    "lib/mimetype_fu.rb",
    "lib/tasks/mimetype_fu_tasks.rake",
    "mimetype-fu.gemspec",
    "spec/fixtures/file.jpg",
    "spec/fixtures/file.rb",
    "spec/mime_type_spec.rb",
    "spec/spec_helper.rb",
    "test/mimetype_fu_test.rb",
    "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/jeanmartin/mimetype-fu}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.7.2}
  s.summary = %q{get the mimetype of a file directly in Ruby}
  s.test_files = [
    "spec/fixtures/file.rb",
    "spec/mime_type_spec.rb",
    "spec/spec_helper.rb",
    "test/mimetype_fu_test.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

